// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

module.exports = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+alias:(.+)$': './packages/alias/src/$1',
    '^multiverse\\+analyze:(.+)$': './packages/analyze/src/$1',
    '^multiverse\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/src/$1',
    '^multiverse\\+fs:(.+)$': './packages/fs/src/$1',
    '^multiverse\\+types:(.+)$': './packages/types/src/$1',
    '^multiverse\\+alias$': './packages/alias/src/index.js',
    '^multiverse\\+analyze$': './packages/analyze/src/index.js',
    '^multiverse\\+bidirectional\\x2dresolve$':
      './packages/bidirectional-resolve/src/index.js',
    '^multiverse\\+fs$': './packages/fs/src/index.js',
    '^multiverse\\+types$': './packages/types/src/index.js',
    '^rootverse\\+alias:(.+)$': './packages/alias/$1',
    '^rootverse\\+analyze:(.+)$': './packages/analyze/$1',
    '^rootverse\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/$1',
    '^rootverse\\+fs:(.+)$': './packages/fs/$1',
    '^rootverse\\+types:(.+)$': './packages/types/$1',
    '^rootverse:(.+)$': './$1',
    '^universe\\+alias:(.+)$': './packages/alias/src/$1',
    '^universe\\+analyze:(.+)$': './packages/analyze/src/$1',
    '^universe\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/src/$1',
    '^universe\\+fs:(.+)$': './packages/fs/src/$1',
    '^universe\\+types:(.+)$': './packages/types/src/$1',
    '^universe\\+alias$': './packages/alias/src/index.js',
    '^universe\\+analyze$': './packages/analyze/src/index.js',
    '^universe\\+bidirectional\\x2dresolve$':
      './packages/bidirectional-resolve/src/index.js',
    '^universe\\+fs$': './packages/fs/src/index.js',
    '^universe\\+types$': './packages/types/src/index.js',
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse\\+alias:(.+)$': './packages/alias/test/$1',
    '^testverse\\+analyze:(.+)$': './packages/analyze/test/$1',
    '^testverse\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/test/$1',
    '^testverse\\+fs:(.+)$': './packages/fs/test/$1',
    '^testverse\\+types:(.+)$': './packages/types/test/$1',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1'
  };
}
