// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

module.exports = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/src/$1',
    '^multiverse\\+common:(.+)$': './packages/common/src/$1',
    '^multiverse\\+fs:(.+)$': './packages/fs/src/$1',
    '^multiverse\\+graph:(.+)$': './packages/graph/src/$1',
    '^multiverse\\+types:(.+)$': './packages/types/src/$1',
    '^multiverse\\+bidirectional\\x2dresolve$':
      './packages/bidirectional-resolve/src/index.js',
    '^multiverse\\+common$': './packages/common/src/index.js',
    '^multiverse\\+fs$': './packages/fs/src/index.js',
    '^multiverse\\+graph$': './packages/graph/src/index.js',
    '^multiverse\\+types$': './packages/types/src/index.js',
    '^rootverse\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/$1',
    '^rootverse\\+common:(.+)$': './packages/common/$1',
    '^rootverse\\+fs:(.+)$': './packages/fs/$1',
    '^rootverse\\+graph:(.+)$': './packages/graph/$1',
    '^rootverse\\+types:(.+)$': './packages/types/$1',
    '^rootverse:(.+)$': './$1',
    '^universe\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/src/$1',
    '^universe\\+common:(.+)$': './packages/common/src/$1',
    '^universe\\+fs:(.+)$': './packages/fs/src/$1',
    '^universe\\+graph:(.+)$': './packages/graph/src/$1',
    '^universe\\+types:(.+)$': './packages/types/src/$1',
    '^universe\\+bidirectional\\x2dresolve$':
      './packages/bidirectional-resolve/src/index.js',
    '^universe\\+common$': './packages/common/src/index.js',
    '^universe\\+fs$': './packages/fs/src/index.js',
    '^universe\\+graph$': './packages/graph/src/index.js',
    '^universe\\+types$': './packages/types/src/index.js',
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse\\+bidirectional\\x2dresolve:(.+)$':
      './packages/bidirectional-resolve/test/$1',
    '^testverse\\+common:(.+)$': './packages/common/test/$1',
    '^testverse\\+fs:(.+)$': './packages/fs/test/$1',
    '^testverse\\+graph:(.+)$': './packages/graph/test/$1',
    '^testverse\\+types:(.+)$': './packages/types/test/$1',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1'
  };
}
