// @ts-check

import {
  assertEnvironment,
  moduleExport
} from '@-xun/symbiote/assets/eslint.config.mjs';

import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:eslint' });

const config = moduleExport({
  derivedAliases: getEslintAliases(),
  ...(await assertEnvironment())
});

config.push({
  /* Add custom config here, such as disabling certain rules */
});

export default config;

debug('exported config: %O', config);

function getEslintAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return [
    ['multiverse+alias:*', './packages/alias/src/*'],
    ['multiverse+analyze:*', './packages/analyze/src/*'],
    ['multiverse+bidirectional-resolve:*', './packages/bidirectional-resolve/src/*'],
    ['multiverse+fs:*', './packages/fs/src/*'],
    ['multiverse+types:*', './packages/types/src/*'],
    ['multiverse+alias', './packages/alias/src/index.ts'],
    ['multiverse+analyze', './packages/analyze/src/index.ts'],
    [
      'multiverse+bidirectional-resolve',
      './packages/bidirectional-resolve/src/index.ts'
    ],
    ['multiverse+fs', './packages/fs/src/index.ts'],
    ['multiverse+types', './packages/types/src/index.ts'],
    ['rootverse+alias:*', './packages/alias/*'],
    ['rootverse+analyze:*', './packages/analyze/*'],
    ['rootverse+bidirectional-resolve:*', './packages/bidirectional-resolve/*'],
    ['rootverse+fs:*', './packages/fs/*'],
    ['rootverse+types:*', './packages/types/*'],
    ['rootverse:*', './*'],
    ['universe+alias:*', './packages/alias/src/*'],
    ['universe+analyze:*', './packages/analyze/src/*'],
    ['universe+bidirectional-resolve:*', './packages/bidirectional-resolve/src/*'],
    ['universe+fs:*', './packages/fs/src/*'],
    ['universe+types:*', './packages/types/src/*'],
    ['universe+alias', './packages/alias/src/index.ts'],
    ['universe+analyze', './packages/analyze/src/index.ts'],
    ['universe+bidirectional-resolve', './packages/bidirectional-resolve/src/index.ts'],
    ['universe+fs', './packages/fs/src/index.ts'],
    ['universe+types', './packages/types/src/index.ts'],
    ['universe:*', './src/*'],
    ['universe', './src/index.ts'],
    ['testverse+alias:*', './packages/alias/test/*'],
    ['testverse+analyze:*', './packages/analyze/test/*'],
    ['testverse+bidirectional-resolve:*', './packages/bidirectional-resolve/test/*'],
    ['testverse+fs:*', './packages/fs/test/*'],
    ['testverse+types:*', './packages/types/test/*'],
    ['testverse:*', './test/*'],
    ['typeverse:*', './types/*']
  ];
}
