// @ts-check
'use strict';

import { deepMergeConfig } from '@-xun/symbiote/assets';
import { assertEnvironment, moduleExport } from '@-xun/symbiote/assets/jest.config.mjs';
import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:jest' });

const config = deepMergeConfig(
  moduleExport({ derivedAliases: getJestAliases(), ...assertEnvironment() }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

export default config;

debug('exported config: %O', config);

function getJestAliases() {
  const extension = process.env.SYMBIOTE_TEST_JEST_TRANSPILED ? 'js' : 'ts';

  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+bidirectional\\x2dresolve:(.+)$':
      '<rootDir>/packages/bidirectional-resolve/src/$1',
    '^multiverse\\+common:(.+)$': '<rootDir>/packages/common/src/$1',
    '^multiverse\\+fs:(.+)$': '<rootDir>/packages/fs/src/$1',
    '^multiverse\\+graph:(.+)$': '<rootDir>/packages/graph/src/$1',
    '^multiverse\\+types:(.+)$': '<rootDir>/packages/types/src/$1',
    '^multiverse\\+bidirectional\\x2dresolve$': `<rootDir>/packages/bidirectional-resolve/src/index.${extension}`,
    '^multiverse\\+common$': `<rootDir>/packages/common/src/index.${extension}`,
    '^multiverse\\+fs$': `<rootDir>/packages/fs/src/index.${extension}`,
    '^multiverse\\+graph$': `<rootDir>/packages/graph/src/index.${extension}`,
    '^multiverse\\+types$': `<rootDir>/packages/types/src/index.${extension}`,
    '^universe\\+bidirectional\\x2dresolve:(.+)$':
      '<rootDir>/packages/bidirectional-resolve/src/$1',
    '^universe\\+common:(.+)$': '<rootDir>/packages/common/src/$1',
    '^universe\\+fs:(.+)$': '<rootDir>/packages/fs/src/$1',
    '^universe\\+graph:(.+)$': '<rootDir>/packages/graph/src/$1',
    '^universe\\+types:(.+)$': '<rootDir>/packages/types/src/$1',
    '^universe\\+bidirectional\\x2dresolve$': `<rootDir>/packages/bidirectional-resolve/src/index.${extension}`,
    '^universe\\+common$': `<rootDir>/packages/common/src/index.${extension}`,
    '^universe\\+fs$': `<rootDir>/packages/fs/src/index.${extension}`,
    '^universe\\+graph$': `<rootDir>/packages/graph/src/index.${extension}`,
    '^universe\\+types$': `<rootDir>/packages/types/src/index.${extension}`,
    '^universe:(.+)$': '<rootDir>/src/$1',
    '^universe$': `<rootDir>/src/index.${extension}`,
    '^testverse\\+bidirectional\\x2dresolve:(.+)$':
      '<rootDir>/packages/bidirectional-resolve/test/$1',
    '^testverse\\+common:(.+)$': '<rootDir>/packages/common/test/$1',
    '^testverse\\+fs:(.+)$': '<rootDir>/packages/fs/test/$1',
    '^testverse\\+graph:(.+)$': '<rootDir>/packages/graph/test/$1',
    '^testverse\\+types:(.+)$': '<rootDir>/packages/types/test/$1',
    '^testverse:(.+)$': '<rootDir>/test/$1',
    '^typeverse:(.+)$': '<rootDir>/types/$1',
    '^rootverse\\+bidirectional\\x2dresolve:(.+)$':
      '<rootDir>/packages/bidirectional-resolve/$1',
    '^rootverse\\+common:(.+)$': '<rootDir>/packages/common/$1',
    '^rootverse\\+fs:(.+)$': '<rootDir>/packages/fs/$1',
    '^rootverse\\+graph:(.+)$': '<rootDir>/packages/graph/$1',
    '^rootverse\\+types:(.+)$': '<rootDir>/packages/types/$1',
    '^rootverse:(.+)$': '<rootDir>/$1'
  };
}
