// !!! DO NOT EDIT THIS FILE DIRECTLY !!!
// ! Edit next.config.babel.js and execute `gulp regenerate-next-config
// ! to make any durable changes. The command will wholesale overwrite this file

require('@babel/register');

module.exports = require('./next.config.babel');
